Blog Post: Add link to report non-.gov
cisagov/getgov-home pull request #92
Opened 2023-09-21 15:49 UTC by Katherine-Osos

## Changes proposed in this pull request:
Added link for reporting .gov domains

This update relates to #[766](https://github.com/cisagov/getgov/issues/766)

2023-09-21 16:18 UTC, Katherine-Osos commented
Changes can be reviewed at [this link](https://federalist-877ab29f-16f6-4f12-961c-96cf064cf070.sites.pages.cloud.gov/preview/cisagov/getgov-home/ko/link-for-non-dotgov/posts/2023-02-08-OMB-new-requirements-for-federal-executive-agencies/)

2023-10-24 18:53 UTC, h-m-f-t requested changes
Thanks! Small change requested.

2023-10-24 18:53 UTC, h-m-f-t commented on posts/2023-02-08-OMB-new-requirements-for-federal-executive-agencies.md
> +- Agencies must **continue to report use of non-.gov domains** [How do they do this](https://search.gov/about/policy/govt-urls.html){.usa-link--external}?
I think we should change 

> How do they do this?

to

> Report at search.gov.

2023-10-26 20:32 UTC, Katherine-Osos commented on posts/2023-02-08-OMB-new-requirements-for-federal-executive-agencies.md
> +- Agencies must **continue to report use of non-.gov domains** [How do they do this](https://search.gov/about/policy/govt-urls.html){.usa-link--external}?
Updated!

2023-10-27 13:13 UTC, h-m-f-t approved these changes
Thanks!

2023-10-31 04:06 UTC, merged